// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package config

import (
	externalRef0 "github.com/kube-nfv/kube-vim/internal/config"
)

// Defines values for TolerationEffect.
const (
	NoExecute        TolerationEffect = "NoExecute"
	NoSchedule       TolerationEffect = "NoSchedule"
	PreferNoSchedule TolerationEffect = "PreferNoSchedule"
)

// Defines values for TolerationOperator.
const (
	Equal  TolerationOperator = "Equal"
	Exists TolerationOperator = "Exists"
)

// ComputeConfig Configuration for compute resource scheduling.
type ComputeConfig struct {
	// NodeSelector Node selector labels for VM placement.
	NodeSelector *map[string]string `json:"nodeSelector,omitempty"`

	// Tolerations Tolerations for VM scheduling.
	Tolerations *[]Toleration `json:"tolerations,omitempty"`
}

// Config Top-level configuration node for kube-vim.
type Config struct {
	// Compute Configuration for compute resource scheduling.
	Compute *ComputeConfig `json:"compute,omitempty"`

	// Image Configuration for kube-vim image providers.
	Image *ImageConfig `json:"image,omitempty"`

	// K8s Configuration related to Kubernetes operations.
	K8s *K8sConfig `json:"k8s,omitempty"`

	// Network Configuration for kube-vim cluster static network.
	Network *NetworkConfig `json:"network,omitempty"`

	// Service Configuration related to the kube-vim service.
	Service *ServiceConfig `json:"service,omitempty"`
}

// GlanceImageConfig Configuration for Glance image provider.
type GlanceImageConfig = map[string]interface{}

// HttpImageConfig Configuration for HTTP image provider.
type HttpImageConfig = map[string]interface{}

// ImageConfig Configuration for kube-vim image providers.
type ImageConfig struct {
	// Glance Configuration for Glance image provider.
	Glance *GlanceImageConfig `json:"glance,omitempty"`

	// Http Configuration for HTTP image provider.
	Http *HttpImageConfig `json:"http,omitempty"`

	// Local Configuration for Local image provider.
	Local *LocalImageConfig `json:"local,omitempty"`

	// StorageClass Kubernetes StorageClass for software image PVCs. By default 'default' storageClass will be used
	StorageClass *string `json:"storageClass,omitempty"`
}

// K8sConfig Configuration related to Kubernetes operations.
type K8sConfig struct {
	// Config Specific path to find k8s config file. By default k8s ServiceAccount place is used
	Config *string `json:"config,omitempty"`

	// Namespace Kubernetes namespace where kube-vim operates. Default is 'kube-nfv'.
	Namespace *string `json:"namespace,omitempty"`
}

// LocalImageConfig Configuration for Local image provider.
type LocalImageConfig struct {
	// Location Location where to locate images.
	Location *string `json:"location,omitempty"`
}

// ManagementNetworkConfig Optional kube-vim-managed shared management network used by an NFVO
// (e.g. OSM) for control-plane reachability to VMs. When enabled,
// kube-vim ensures a kube-OVN Vpc + Subnet + NetworkAttachmentDefinition
// exist at startup with all the labels kube-vim's internal lookups
// require. The trio is reconciled on every kube-vim restart and never
// deleted by NS termination.
type ManagementNetworkConfig struct {
	// Cidr Subnet CIDR. Must not overlap with the cluster pod or service CIDR. Updates are not applied to running subnets to avoid disrupting workloads.
	Cidr *string `json:"cidr,omitempty"`

	// Enabled Whether kube-vim should provision and own the management network. Default off; opt-in.
	Enabled *bool `json:"enabled,omitempty"`

	// ExcludeIps Optional list of IPs (or ranges) to exclude from IPAM allocation.
	ExcludeIps *[]string `json:"excludeIps,omitempty"`

	// Gateway Optional gateway IP. Defaults to the first usable address of `cidr`.
	Gateway *string `json:"gateway,omitempty"`

	// Name kube-OVN Vpc name. Used as the base for the subnet name (`{name}-subnet-0`) and the default NetworkAttachmentDefinition name.
	Name *string `json:"name,omitempty"`

	// NetAttachDefName NetworkAttachmentDefinition name. Defaults to `{subnet-name}-netattach` to match kube-vim's existing convention.
	NetAttachDefName *string `json:"netAttachDefName,omitempty"`

	// NetAttachDefNamespace Namespace of the NetworkAttachmentDefinition. Defaults to the kube-vim namespace from the `k8s` section.
	NetAttachDefNamespace *string `json:"netAttachDefNamespace,omitempty"`
}

// NetworkConfig Configuration for kube-vim cluster static network.
type NetworkConfig struct {
	// ManagementNetwork Optional kube-vim-managed shared management network used by an NFVO
	// (e.g. OSM) for control-plane reachability to VMs. When enabled,
	// kube-vim ensures a kube-OVN Vpc + Subnet + NetworkAttachmentDefinition
	// exist at startup with all the labels kube-vim's internal lookups
	// require. The trio is reconciled on every kube-vim restart and never
	// deleted by NS termination.
	ManagementNetwork *ManagementNetworkConfig `json:"managementNetwork,omitempty"`

	// Sriov Settings applied to every SR-IOV network kube-vim creates. SR-IOV
	// networks are rendered as ovs-cni NetworkAttachmentDefinitions so the
	// VF representor is attached to an OVS bridge, enabling OVS hardware
	// offload of the VF traffic. ovs-cni auto-discovers the bridge from the
	// VF's PF (the PF uplink must already be a port on the bridge), which is
	// the correct behaviour for multi-PF hosts where each PF has its own
	// bridge.
	Sriov *SriovNetworkConfig `json:"sriov,omitempty"`
}

// ServerConfig Kube-vim Server configuration.
type ServerConfig struct {
	// Port "A TCP port number specifies the endpoint for network communication on the service.
	// Port numbers range from 1 to 65535, with the lower range (1-1023) typically reserved for well-known services and system processes.
	// It is important to choose a port within the allowed range that does not conflict with other services running on the host.
	//
	// Ensure that the selected port is open and accessible for communication while respecting the security policies of your network.
	// Avoid using ports that are commonly blocked by firewalls or reserved for specific applications."
	Port *externalRef0.Port `json:"port,omitempty"`

	// Tls "TLS server configuration defines the settings for establishing secure TLS communication on the server-side. This configuration
	// ensures that the server can securely encrypt data with clients, protecting against eavesdropping, tampering, and forgery.
	// The configuration includes settings for the server's x.509 certificate and private key, which are essential for the TLS handshake."
	Tls *externalRef0.TlsServerConfig `json:"tls,omitempty"`
}

// ServiceConfig Configuration related to the kube-vim service.
type ServiceConfig struct {
	// LogLevel "Log level defines the severity of messages that will be recorded in the application's
	// logs. The available log levels are:
	// - 'trace': Provides the most detailed logging, often used for debugging specific issues.
	// - 'debug': Includes less verbose logging than 'trace', typically for development and debugging purposes.
	// - 'info': Standard logging level that provides general application flow and operational information.
	// - 'warn': Logs warnings that highlight potential issues or unexpected conditions that do not necessarily indicate a failure.
	// - 'error': Logs errors that indicate a failure or significant issue in the application.
	//
	// The default value is 'info', which strikes a balance between verbosity and usefulness for most environments."
	LogLevel *externalRef0.LogLevel `json:"logLevel,omitempty"`

	// Server Kube-vim Server configuration.
	Server *ServerConfig `json:"server,omitempty"`
}

// SriovNetworkConfig Settings applied to every SR-IOV network kube-vim creates. SR-IOV
// networks are rendered as ovs-cni NetworkAttachmentDefinitions so the
// VF representor is attached to an OVS bridge, enabling OVS hardware
// offload of the VF traffic. ovs-cni auto-discovers the bridge from the
// VF's PF (the PF uplink must already be a port on the bridge), which is
// the correct behaviour for multi-PF hosts where each PF has its own
// bridge.
type SriovNetworkConfig struct {
	// SocketFile OVSDB socket ovs-cni connects to. Defaults to the standard path;
	// on kube-OVN/Talos hosts the socket lives at /run/openvswitch/db.sock
	// (reachable via the /var/run -> /run symlink, or set explicitly).
	SocketFile *string `json:"socketFile,omitempty"`
}

// Toleration Kubernetes toleration for pod/VM scheduling.
type Toleration struct {
	Effect            *TolerationEffect   `json:"effect,omitempty"`
	Key               *string             `json:"key,omitempty"`
	Operator          *TolerationOperator `json:"operator,omitempty"`
	TolerationSeconds *int64              `json:"tolerationSeconds,omitempty"`
	Value             *string             `json:"value,omitempty"`
}

// TolerationEffect defines model for Toleration.Effect.
type TolerationEffect string

// TolerationOperator defines model for Toleration.Operator.
type TolerationOperator string
