// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kube-nfv/kube-vim/internal/kubevim/image (interfaces: NfvImageManager)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_manager.go -package=mock github.com/kube-nfv/kube-vim/internal/kubevim/image NfvImageManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apis "github.com/kube-nfv/kube-vim-api/pkg/apis"
	vivnfm "github.com/kube-nfv/kube-vim-api/pkg/apis/vivnfm"
	gomock "go.uber.org/mock/gomock"
)

// MockNfvImageManager is a mock of NfvImageManager interface.
type MockNfvImageManager struct {
	ctrl     *gomock.Controller
	recorder *MockNfvImageManagerMockRecorder
	isgomock struct{}
}

// MockNfvImageManagerMockRecorder is the mock recorder for MockNfvImageManager.
type MockNfvImageManagerMockRecorder struct {
	mock *MockNfvImageManager
}

// NewMockNfvImageManager creates a new mock instance.
func NewMockNfvImageManager(ctrl *gomock.Controller) *MockNfvImageManager {
	mock := &MockNfvImageManager{ctrl: ctrl}
	mock.recorder = &MockNfvImageManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNfvImageManager) EXPECT() *MockNfvImageManagerMockRecorder {
	return m.recorder
}

// GetImage mocks base method.
func (m *MockNfvImageManager) GetImage(arg0 context.Context, arg1 *apis.Identifier) (*vivnfm.SoftwareImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", arg0, arg1)
	ret0, _ := ret[0].(*vivnfm.SoftwareImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockNfvImageManagerMockRecorder) GetImage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockNfvImageManager)(nil).GetImage), arg0, arg1)
}

// ListImages mocks base method.
func (m *MockNfvImageManager) ListImages(arg0 context.Context) ([]*vivnfm.SoftwareImageInformation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", arg0)
	ret0, _ := ret[0].([]*vivnfm.SoftwareImageInformation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockNfvImageManagerMockRecorder) ListImages(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockNfvImageManager)(nil).ListImages), arg0)
}
