// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock/mock_manager.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	vivnfm "github.com/kube-nfv/kube-vim-api/pkg/apis/vivnfm"
	config "github.com/kube-nfv/kube-vim/internal/config/kubevim"
	network "github.com/kube-nfv/kube-vim/internal/kubevim/network"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateNetwork mocks base method.
func (m *MockManager) CreateNetwork(arg0 context.Context, arg1 string, arg2 *vivnfm.VirtualNetworkData) (*vivnfm.VirtualNetwork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", arg0, arg1, arg2)
	ret0, _ := ret[0].(*vivnfm.VirtualNetwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockManagerMockRecorder) CreateNetwork(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockManager)(nil).CreateNetwork), arg0, arg1, arg2)
}

// CreateSubnet mocks base method.
func (m *MockManager) CreateSubnet(arg0 context.Context, arg1 string, arg2 *vivnfm.NetworkSubnetData) (*vivnfm.NetworkSubnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", arg0, arg1, arg2)
	ret0, _ := ret[0].(*vivnfm.NetworkSubnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockManagerMockRecorder) CreateSubnet(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockManager)(nil).CreateSubnet), arg0, arg1, arg2)
}

// DeleteNetwork mocks base method.
func (m *MockManager) DeleteNetwork(arg0 context.Context, arg1 ...network.GetNetworkOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteNetwork", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockManagerMockRecorder) DeleteNetwork(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockManager)(nil).DeleteNetwork), varargs...)
}

// DeleteSubnet mocks base method.
func (m *MockManager) DeleteSubnet(arg0 context.Context, arg1 ...network.GetSubnetOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSubnet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnet indicates an expected call of DeleteSubnet.
func (mr *MockManagerMockRecorder) DeleteSubnet(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnet", reflect.TypeOf((*MockManager)(nil).DeleteSubnet), varargs...)
}

// EnsureManagementNetwork mocks base method.
func (m *MockManager) EnsureManagementNetwork(arg0 context.Context, arg1 *config.ManagementNetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureManagementNetwork", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureManagementNetwork indicates an expected call of EnsureManagementNetwork.
func (mr *MockManagerMockRecorder) EnsureManagementNetwork(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureManagementNetwork", reflect.TypeOf((*MockManager)(nil).EnsureManagementNetwork), arg0, arg1)
}

// GetNetwork mocks base method.
func (m *MockManager) GetNetwork(arg0 context.Context, arg1 ...network.GetNetworkOpt) (*vivnfm.VirtualNetwork, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNetwork", varargs...)
	ret0, _ := ret[0].(*vivnfm.VirtualNetwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetwork indicates an expected call of GetNetwork.
func (mr *MockManagerMockRecorder) GetNetwork(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetwork", reflect.TypeOf((*MockManager)(nil).GetNetwork), varargs...)
}

// GetSubnet mocks base method.
func (m *MockManager) GetSubnet(arg0 context.Context, arg1 ...network.GetSubnetOpt) (*vivnfm.NetworkSubnet, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSubnet", varargs...)
	ret0, _ := ret[0].(*vivnfm.NetworkSubnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *MockManagerMockRecorder) GetSubnet(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*MockManager)(nil).GetSubnet), varargs...)
}

// ListNetworks mocks base method.
func (m *MockManager) ListNetworks(arg0 context.Context) ([]*vivnfm.VirtualNetwork, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", arg0)
	ret0, _ := ret[0].([]*vivnfm.VirtualNetwork)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockManagerMockRecorder) ListNetworks(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockManager)(nil).ListNetworks), arg0)
}

// ListSubnets mocks base method.
func (m *MockManager) ListSubnets(arg0 context.Context) ([]*vivnfm.NetworkSubnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnets", arg0)
	ret0, _ := ret[0].([]*vivnfm.NetworkSubnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnets indicates an expected call of ListSubnets.
func (mr *MockManagerMockRecorder) ListSubnets(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnets", reflect.TypeOf((*MockManager)(nil).ListSubnets), arg0)
}
