// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock/mock_manager.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	vivnfm "github.com/kube-nfv/kube-vim-api/pkg/apis/vivnfm"
	compute "github.com/kube-nfv/kube-vim/internal/kubevim/compute"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AllocateComputeResource mocks base method.
func (m *MockManager) AllocateComputeResource(arg0 context.Context, arg1 *vivnfm.AllocateComputeRequest) (*vivnfm.VirtualCompute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateComputeResource", arg0, arg1)
	ret0, _ := ret[0].(*vivnfm.VirtualCompute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateComputeResource indicates an expected call of AllocateComputeResource.
func (mr *MockManagerMockRecorder) AllocateComputeResource(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateComputeResource", reflect.TypeOf((*MockManager)(nil).AllocateComputeResource), arg0, arg1)
}

// DeleteComputeResource mocks base method.
func (m *MockManager) DeleteComputeResource(arg0 context.Context, arg1 ...compute.GetComputeOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteComputeResource", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComputeResource indicates an expected call of DeleteComputeResource.
func (mr *MockManagerMockRecorder) DeleteComputeResource(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComputeResource", reflect.TypeOf((*MockManager)(nil).DeleteComputeResource), varargs...)
}

// GetComputeResource mocks base method.
func (m *MockManager) GetComputeResource(arg0 context.Context, arg1 ...compute.GetComputeOpt) (*vivnfm.VirtualCompute, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComputeResource", varargs...)
	ret0, _ := ret[0].(*vivnfm.VirtualCompute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputeResource indicates an expected call of GetComputeResource.
func (mr *MockManagerMockRecorder) GetComputeResource(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputeResource", reflect.TypeOf((*MockManager)(nil).GetComputeResource), varargs...)
}

// ListComputeResources mocks base method.
func (m *MockManager) ListComputeResources(arg0 context.Context) ([]*vivnfm.VirtualCompute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComputeResources", arg0)
	ret0, _ := ret[0].([]*vivnfm.VirtualCompute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComputeResources indicates an expected call of ListComputeResources.
func (mr *MockManagerMockRecorder) ListComputeResources(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComputeResources", reflect.TypeOf((*MockManager)(nil).ListComputeResources), arg0)
}
