openapi: 3.0.0
info:
  title: Kube-Vim Configuration Schema
  version: 1.0.0
components:
  schemas:
    Config:
      type: object
      description: "Top-level configuration node for kube-vim."
      properties:
        service:
          $ref: '#/components/schemas/ServiceConfig'
        k8s:
          $ref: '#/components/schemas/K8sConfig'
        image:
          $ref: '#/components/schemas/ImageConfig'
        network:
          $ref: '#/components/schemas/NetworkConfig'
    ServiceConfig:
      type: object
      description: "Configuration related to the kube-vim service."
      properties:
        port:
          type: integer
          minimum: 1
          maximum: 65535
          default: 50051
          description: "A valid TCP port number (1-65535) for the kube-vim gRPC service. Default is 50051."
        logLevel:
          type: string
          enum:
            - trace
            - debug
            - info
            - warn
            - error
          default: info
          description: "Log level for the kube-vim application. Must be one of 'trace', 'debug', 'info', 'warn', or 'error'. Default is 'info'."
    K8sConfig:
      type: object
      description: "Configuration related to Kubernetes operations."
      properties:
        namespace:
          type: string
          default: "kube-nfv"
          description: "Kubernetes namespace where kube-vim operates. Default is 'kube-nfv'."
        config:
          type: string
          description: "Specific path to find k8s config file. By default k8s ServiceAccount place is used"

    ImageConfig:
      type: object
      description: "Configuration for kube-vim image providers."
      properties:
        http:
          $ref: '#/components/schemas/HttpImageConfig'
        local:
          $ref: '#/components/schemas/LocalImageConfig'
        glance:
          $ref: '#/components/schemas/GlanceImageConfig'
    HttpImageConfig:
      type: object
      description: "Configuration for HTTP image provider."
    LocalImageConfig:
      type: object
      description: "Configuration for Local image provider."
      properties:
        location:
          type: string
          description: "Location where to locate images."
    GlanceImageConfig:
      type: object
      description: "Configuration for Glance image provider."

    NetworkConfig:
      type: object
      description: "Configuration for kube-vim cluster static network."
      properties:
        mgmt:
          type: object
          description: "Configuration for kube-vim management network."
