openapi: 3.0.0
info:
  title: Kube-Vim Gateway Configuration Schema
  version: 1.0.0
components:
  schemas:
    Config:
      type: object
      description: "Top-level configuration node for kube-vim gateway."
      properties:
        service:
          $ref: '#/components/schemas/ServiceConfig'
        kubevim:
          $ref: '#/components/schemas/KubeVimConfig'
    ServiceConfig:
      type: object
      description: "Configuration related to the kube-vim Gateway service."
      properties:
        logLevel:
          $ref: './common.openapi.yaml#/components/schemas/logLevel'
        server:
          $ref: '#/components/schemas/ServerConfig'
    ServerConfig:
      type: object
      description: "Kube-vim Gateway Server configuration."
      properties:
        ip:
          $ref: './common.openapi.yaml#/components/schemas/ipAddress'
          description: "IP address of the kube-vim Gateway server."
          default: 127.0.0.1
        port:
          $ref: './common.openapi.yaml#/components/schemas/port'
          default: 51155
          description: "Kube-vim Gateway server listening port."
        tls:
          $ref: './common.openapi.yaml#/components/schemas/tlsServerConfig'
          description: "Kube-vim Gateway server TLS configuration."
    KubeVimConfig:
      type: object
      description: "Kube-vim connection configuration."
      properties:
        url:
          type: string
          description: "URL of the kube-vim gRPC server. Can be an IP:port (e.g., '127.0.0.1:50051') or a service DNS name (e.g., 'kube-vim:50051'). Typically kube-vim launches in a separate pod in Kubernetes, so using the service name is recommended."
          default: "kube-vim:50051"
          pattern: '^[a-zA-Z0-9.-]+:[0-9]+$'
        tls:
          $ref: './common.openapi.yaml#/components/schemas/tlsClientConfig'
          description: |
            "TLS configuration for the kube-vim server connection. In most cases TLS is not needed since both kube-vim and
            gateway launch in the same namespace and communication is performed over cluster network."
