// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package config

// Defines values for ServiceConfigLogLevel.
const (
	Debug ServiceConfigLogLevel = "debug"
	Error ServiceConfigLogLevel = "error"
	Info  ServiceConfigLogLevel = "info"
	Trace ServiceConfigLogLevel = "trace"
	Warn  ServiceConfigLogLevel = "warn"
)

// Config Top-level configuration node for kube-vim.
type Config struct {
	// Image Configuration for kube-vim image providers.
	Image *ImageConfig `json:"image,omitempty"`

	// K8s Configuration related to Kubernetes operations.
	K8s *K8sConfig `json:"k8s,omitempty"`

	// Network Configuration for kube-vim cluster static network.
	Network *NetworkConfig `json:"network,omitempty"`

	// Service Configuration related to the kube-vim service.
	Service *ServiceConfig `json:"service,omitempty"`
}

// GlanceImageConfig Configuration for Glance image provider.
type GlanceImageConfig = map[string]interface{}

// HttpImageConfig Configuration for HTTP image provider.
type HttpImageConfig = map[string]interface{}

// ImageConfig Configuration for kube-vim image providers.
type ImageConfig struct {
	// Glance Configuration for Glance image provider.
	Glance *GlanceImageConfig `json:"glance,omitempty"`

	// Http Configuration for HTTP image provider.
	Http *HttpImageConfig `json:"http,omitempty"`

	// Local Configuration for Local image provider.
	Local *LocalImageConfig `json:"local,omitempty"`
}

// K8sConfig Configuration related to Kubernetes operations.
type K8sConfig struct {
	// Config Specific path to find k8s config file. By default k8s ServiceAccount place is used
	Config *string `json:"config,omitempty"`

	// Namespace Kubernetes namespace where kube-vim operates. Default is 'kube-nfv'.
	Namespace *string `json:"namespace,omitempty"`
}

// LocalImageConfig Configuration for Local image provider.
type LocalImageConfig struct {
	// Location Location where to locate images.
	Location *string `json:"location,omitempty"`
}

// NetworkConfig Configuration for kube-vim cluster static network.
type NetworkConfig struct {
	// Mgmt Configuration for kube-vim management network.
	Mgmt *map[string]interface{} `json:"mgmt,omitempty"`
}

// ServerConfig Kube-vim Server configuration.
type ServerConfig struct {
	// Port A valid TCP port number (1-65535) for the kube-vim gRPC service. Default is 50051.
	Port *int `json:"port,omitempty"`

	// Tls Kube-vim server TLS configuration.
	Tls *struct {
		// Cert Path to the x.509 certificate
		Cert *string `json:"cert,omitempty"`

		// Key Path to the x.509 private key
		Key *string `json:"key,omitempty"`
	} `json:"tls,omitempty"`
}

// ServiceConfig Configuration related to the kube-vim service.
type ServiceConfig struct {
	// LogLevel Log level for the kube-vim application. Must be one of 'trace', 'debug', 'info', 'warn', or 'error'. Default is 'info'.
	LogLevel *ServiceConfigLogLevel `json:"logLevel,omitempty"`

	// Server Kube-vim Server configuration.
	Server *ServerConfig `json:"server,omitempty"`
}

// ServiceConfigLogLevel Log level for the kube-vim application. Must be one of 'trace', 'debug', 'info', 'warn', or 'error'. Default is 'info'.
type ServiceConfigLogLevel string
