// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock/mock_manager.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apis "github.com/kube-nfv/kube-vim-api/pkg/apis"
	vivnfm "github.com/kube-nfv/kube-vim-api/pkg/apis/vivnfm"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateFlavour mocks base method.
func (m *MockManager) CreateFlavour(arg0 context.Context, arg1 *vivnfm.VirtualComputeFlavour) (*apis.Identifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlavour", arg0, arg1)
	ret0, _ := ret[0].(*apis.Identifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFlavour indicates an expected call of CreateFlavour.
func (mr *MockManagerMockRecorder) CreateFlavour(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlavour", reflect.TypeOf((*MockManager)(nil).CreateFlavour), arg0, arg1)
}

// DeleteFlavour mocks base method.
func (m *MockManager) DeleteFlavour(arg0 context.Context, arg1 *apis.Identifier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlavour", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlavour indicates an expected call of DeleteFlavour.
func (mr *MockManagerMockRecorder) DeleteFlavour(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlavour", reflect.TypeOf((*MockManager)(nil).DeleteFlavour), arg0, arg1)
}

// GetFlavour mocks base method.
func (m *MockManager) GetFlavour(arg0 context.Context, arg1 *apis.Identifier) (*vivnfm.VirtualComputeFlavour, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlavour", arg0, arg1)
	ret0, _ := ret[0].(*vivnfm.VirtualComputeFlavour)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlavour indicates an expected call of GetFlavour.
func (mr *MockManagerMockRecorder) GetFlavour(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlavour", reflect.TypeOf((*MockManager)(nil).GetFlavour), arg0, arg1)
}

// GetFlavours mocks base method.
func (m *MockManager) GetFlavours(arg0 context.Context) ([]*vivnfm.VirtualComputeFlavour, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlavours", arg0)
	ret0, _ := ret[0].([]*vivnfm.VirtualComputeFlavour)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlavours indicates an expected call of GetFlavours.
func (mr *MockManagerMockRecorder) GetFlavours(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlavours", reflect.TypeOf((*MockManager)(nil).GetFlavours), arg0)
}
